# Generated by Django 4.2.2 on 2023-06-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='likes',
            new_name='post',
        ),
    ]
