# Generated by Django 4.2.2 on 2023-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_likes_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users', to='network.post'),
        ),
    ]
