# Generated by Django 4.2.2 on 2023-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='postLikes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='network.post'),
        ),
    ]
