# Generated by Django 4.2.2 on 2023-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_user_post_author_alter_user_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='postLikes',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='network.post'),
        ),
    ]
